spring.application.name=Inscription

# Base de donnees MySQL
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=MDAzDtQREfKcuxJzceYJjFqiivSdYBEd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Serveur
server.port=${PORT:8081}
server.forward-headers-strategy=framework

# URL de base
app.base-url=https://inscription-cours-production-a068.up.railway.app

# Email SMTP
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=466bb5f161152f
spring.mail.password=0b027e2d384e76
mailtrap.api.token=${MAILTRAP_API_TOKEN:481bcb2eb6a894ea8ef6eea7b312d792}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
