spring.application.name=Inscription

# Base de donnees MySQL
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=MDAzDtQREfKcuxJzceYJjFqiivSdYBEd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Serveur
server.port=${PORT:8081}
server.forward-headers-strategy=framework

# URL de base
app.base-url=https://inscription-cours-production-a068.up.railway.app

# Mailtrap API token
mailtrap.api.token=${MAILTRAP_API_TOKEN:39650f47c4dd5c281b3fb1fbc598084e}
mailtrap.inbox.id=${MAILTRAP_INBOX_ID:4675903}